### ISSUE TITLE
Missing lines in C6649 / C2128 symbol

### ISSUE THREAD

**Issue by Bouni** [uPesy/easyeda2kicad.py#53]
I just discoverd that there's one line missing for the diode in the optocoupler `C6649` as well as the diode `C2128`:

![image](https://user-images.githubusercontent.com/948965/173518788-dc7f4307-3a50-4c76-abb5-6c13d2043649.png)

![image](https://user-images.githubusercontent.com/948965/173518894-db0e25d6-23dd-40a3-bcf7-5803589645cd.png)

![image](https://user-images.githubusercontent.com/948965/173519408-20e4a855-a1f0-47c1-83f9-661c8681a0a4.png)

![image](https://user-images.githubusercontent.com/948965/173519538-8dfaf1c1-d838-4565-94a6-f436ae49ee27.png)

**Comment by uPesy** [comment]
Should be fixed in version 0.4.2 on the dev branch

**Comment by Bouni** [comment]
`C6649` works for me in 0.4.2 but `C2128` is still the same:

![image](https://user-images.githubusercontent.com/948965/173792076-e1a9e1f8-2dee-4130-8c01-90042d056d4f.png)

![image](https://user-images.githubusercontent.com/948965/173792157-be7faef6-212e-4759-a96d-cd80c9f41884.png)

**Comment by uPesy** [comment]
On my side it's working great too for `C2128` 
![image](https://user-images.githubusercontent.com/61392244/174428790-491fe559-174a-4637-82d8-cb45e6513b6d.png)

**Comment by uPesy** [comment]
In fact, it's because the lib update features doesn't work with this particular ID with `(` and `)` in the regex.
It's fixed in the last version on the dev branch.

**Comment by Bouni** [comment]
:tada: Works for me now!
